# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-13 06:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_course_teachers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Teachers',
        ),
    ]
